### ISSUE TITLE
OBO foundry review

### ISSUE THREAD

**Issue by matentzn** [luis-gonzalez-m/Collembola#5]
@luis-gonzalez-m Thanks for all the work you did for improving CLAO. I argue for your case at the next meeting, so you dont need to do anything anymore! Thank you!

To move on, please update this information (you can just do it in this github issue):

```
---
layout: ontology_detail
id: clao
title: The Collembola Development and Anatomy Ontology
build:
  checkout: git clone https://github.com/luis-gonzalez-m/Collembola.git
  system: git
  path: "."
contact:
  email: YOUREMAIL
  label: YOURNAME
description: An ontology for the development and anatomy of [...]
domain: anatomy
homepage: https://github.com/luis-gonzalez-m/Collembola
products:
  - id: clao.owl
  - id: clao.obo
dependencies:
 - id: ro
tracker: https://github.com/luis-gonzalez-m/Collembola/issues
license:
  url: http://creativecommons.org/publicdomain/zero/1.0/
  label: CC-0
activity_status: active
---

The Collembola Development and Anatomy Ontology (CLAO) is to describe the anatomy and development of [...]. This ontology is intended to be used for [...]. The ontology was created by [...], and is used by [...]
```

You can change the description text in any way you want. It is good practice to list intended and actual use.

I will add my final review to https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1189
